// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, discord_id, onboarding_complete, email, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DiscordID,
		&i.OnboardingComplete,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, name, discord_id, onboarding_complete, email, created_at FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DiscordID,
			&i.OnboardingComplete,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWithEmail = `-- name: GetUsersWithEmail :many
SELECT id, name, discord_id, onboarding_complete, email, created_at FROM users WHERE email != '' AND email IS NOT NULL
`

func (q *Queries) GetUsersWithEmail(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersWithEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DiscordID,
			&i.OnboardingComplete,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, name, discord_id, onboarding_complete, email)
VALUES ($1, $2, $3, $4, $5)
`

type InsertUserParams struct {
	ID                 string
	Name               string
	DiscordID          string
	OnboardingComplete pgtype.Bool
	Email              string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.Name,
		arg.DiscordID,
		arg.OnboardingComplete,
		arg.Email,
	)
	return err
}
