// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: matchups.sql

package db

import (
	"context"
)

const getMatchupsByYear = `-- name: GetMatchupsByYear :many
SELECT
    id,
    year,
    week,
    is_playoff,
    playoff_round,
    home_user_id,
    away_user_id,
    home_seed,
    away_seed,
    home_score,
    away_score
FROM matchups
WHERE year = $1
ORDER BY week ASC, id ASC
`

func (q *Queries) GetMatchupsByYear(ctx context.Context, year int32) ([]Matchup, error) {
	rows, err := q.db.Query(ctx, getMatchupsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Matchup
	for rows.Next() {
		var i Matchup
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Week,
			&i.IsPlayoff,
			&i.PlayoffRound,
			&i.HomeUserID,
			&i.AwayUserID,
			&i.HomeSeed,
			&i.AwaySeed,
			&i.HomeScore,
			&i.AwayScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
