name: Fetch Player Data
on:
  schedule:
    - cron: "0 0 * * 2"

jobs:
  player-data-update:
    name: player data update
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Latest
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Fetch Player Data
        shell: bash
        run: |
          SLEEPER_LEAGUE_ID=${{ secrets.SLEEPER_LEAGUE_ID }} go run ./tools/fetch-player-data/main.go

      - name: Commit Updated Data
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update player data"
          git push    
