name: High Score Notification
on:
  schedule:
    - cron: "0 13 * * 3"

jobs:
  high-score-notification:
    name: high score notification
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Latest
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: High Score Notification
        shell: bash
        run: |
          SLEEPER_LEAGUE_ID=${{ secrets.SLEEPER_LEAGUE_ID }} DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} DISCORD_USER_ID=${{ secrets.DISCORD_USER_ID }} go run ./tools/high-score-notification/main.go
